#-----------------------------------------------------------------------------------------
# Set which editors to use based on the kinds of files present in each repository.
# Environment variables such as %LocalAppData% are supported.
# Glob patterns are also supported.

# You can also force a repo to use a given editor by creating a file named ".repo-editor"
# in the root of the repo with one line containing the editor's path.
#-----------------------------------------------------------------------------------------


# Editors to use for repos containing these file types.
# If multiple of these file types are present, it will use the most prevalent one.
[[editors]]
extensions = [".py", ".pyw"]
editor = "C:/Program Files/JetBrains/*/*/pycharm64.exe"

[[editors]]
extensions = [".js", ".css", ".html"]
editor = "C:/Program Files/JetBrains/*/*/webstorm64.exe"

[[editors]]
default = true
editor = "%LocalAppData%/Programs/Microsoft VS Code/Code.exe"


#editors = [
#    { extensions = [".py", ".pyw"], editor = "C:/Program Files/JetBrains/*/*/pycharm64.exe" },
#    { extensions = [".js", ".css", ".html"], editor = "C:/Program Files/JetBrains/*/*/webstorm64.exe" },
#    { default = true, editor = "%LocalAppData%/Programs/Microsoft VS Code/bin/code.cmd" },
#]